### ISSUE TITLE
能用，但是不能获取到所有的IIS节点

### ISSUE THREAD

**Issue by hailangbotao** [Yxnt/zabbix-w3wp#4]
大佬，我找了很久，发现只有你的模板和程序是可以自动获取到IIS节点，并实现自动监控IIS节点。但是稍微有点不足，就是不能获取所有的IIS节点呢，不知道为什么会有缺失，你能慷慨地完善一下吗？我能给您的邮箱（yandou@uzai.com）发邮件吗？

**Comment by hailangbotao** [comment]
> 大佬，我找了很久，发现只有你的模板和程序是可以自动获取到IIS节点，并实现自动监控IIS节点。但是稍微有点不足，就是不能获取所有的IIS节点呢，不知道为什么会有缺失，你能慷慨地完善一下吗？我能给您的邮箱（[yandou@uzai.com](mailto:yandou@uzai.com)）发邮件吗？

大佬做的实际上没有问题，我的一些IIS节点由于没有访问量，所以没有工作进程，所以探测不到

**Comment by Yxnt** [comment]
@hailangbotao 不好意思，其实已经从那边公司离职4年多了。后续如果有问题可直接发邮件到  j__xnt@163.com，这个脚本也是刚工作的时候写的，可能平时较忙偶尔才会看下个人的 github 账号。见谅
